#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/isaac/modular_isaac.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_isaac.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright (c) 2024 Perceptron, Inc.  All rights reserved.
# Perceptron, Inc. Non-Production License (2024-01-01)


### 1. Scope and acceptance

# **1.1. Scope of the Agreement.**
# This Agreement applies to any use, modification, or Distribution of any Perceptron Model by You, regardless of the source You obtained a copy of such Perceptron Model.
#
# **1.2. Acceptance.** By accessing, using, modifying, Distributing a Perceptron Model, or by creating, using or distributing a Derivative of the Perceptron Model, You agree to be bound by this Agreement.
#
# **1.3. Acceptance on behalf of a third-party.** If You accept this Agreement on behalf of Your employer or another person or entity, You warrant and represent that You have the authority to act and accept this Agreement on their behalf. In such a case, the word “You” in this Agreement will refer to Your employer or such other person or entity.
#
# ## 2. License
# **2.1. Grant of rights.** Subject to Section 3 below, Perceptron, Inc. hereby grants You a non-exclusive, royalty-free, worldwide, non-sublicensable, non-transferable, limited license to use, copy, modify, and Distribute under the conditions provided in Section 2.2 below, the Perceptron Model and any Derivatives made by or for Perceptron, Inc. and to create Derivatives of the Perceptron Model.
#
# **2.2. Distribution of Perceptron Model and Derivatives made by or for Perceptron, Inc..** Subject to Section 3 below, You may Distribute copies of the Perceptron Model and/or Derivatives made by or for Perceptron, Inc., under the following conditions:
# - You must make available a copy of this Agreement to third-party recipients of the Perceptron Models and/or Derivatives made by or for Perceptron, Inc. you Distribute, it being specified that any rights to use the Perceptron Models and/or Derivatives made by or for Perceptron, Inc. shall be directly granted by Perceptron, Inc. to said third-party recipients pursuant to the Perceptron, Inc. Non-Production License agreement executed between these parties;
# - You must retain in all copies of the Perceptron Models the following attribution notice within a “Notice” text file distributed as part of such copies: “Licensed by Perceptron, Inc. under the Perceptron, Inc. Non-Production License”.
#
# **2.3. Distribution of Derivatives made by or for You.** Subject to Section 3 below, You may Distribute any Derivatives made by or for You under additional or different terms and conditions, provided that:
# - In any event, the use and modification of Perceptron Model and/or Derivatives made by or for Perceptron, Inc. shall remain governed by the terms and conditions of this Agreement;
# - You include in any such Derivatives made by or for You prominent notices stating that You modified the concerned Perceptron Model; and
# - Any terms and conditions You impose on any third-party recipients relating to Derivatives made by or for You shall neither limit such third-party recipients’ use of the Perceptron Model or any Derivatives made by or for Perceptron, Inc. in accordance with the Perceptron, Inc. Non-Production License nor conflict with any of its terms and conditions.
#
# ## 3. Limitations
# **3.1. Misrepresentation.** You must not misrepresent or imply, through any means, that the Derivatives made by or for You and/or any modified version of the Perceptron Model You Distribute under your name and responsibility is an official product of Perceptron, Inc. or has been endorsed, approved or validated by Perceptron, Inc., unless You are authorized by Us to do so in writing.
#
# **3.2. Usage Limitation**
# - You shall only use the Perceptron Models and Derivatives (whether or not created by Perceptron, Inc.) for testing, research, Personal, or evaluation purposes in Non-Production Environments;
# - Subject to the foregoing, You shall not supply the Perceptron Models or Derivatives in the course of a commercial activity, whether in return for payment or free of charge, in any medium or form, including but not limited to through a hosted or managed service (e.g. SaaS, cloud instances, etc.), or behind a software layer.
#
# **3.3. Usage not permitted under this Agreement.** If You want to use a Perceptron Model or a Derivative for any purpose that is not expressly authorized under this Agreement, You must request a license from Perceptron, Inc., which Perceptron, Inc. may grant to You in Perceptron, Inc.’s sole discretion. Please contact Perceptron, Inc. at the following e-mail address if You want to discuss such a license: sales@perceptron.inc
#
# ## 4. Intellectual Property
# **4.1. Trademarks.** No trademark licenses are granted under this Agreement, and in connection with the Perceptron Models, You may not use any name or mark owned by or associated with Perceptron, Inc. or any of its affiliates, except (i) as required for reasonable and customary use in describing and Distributing the Perceptron Models and Derivatives made by or for Perceptron, Inc. and (ii) for attribution purposes as required by this Agreement.
#
# **4.2. Outputs.** We claim no ownership rights in and to the Outputs. You are solely responsible for the Outputs You generate and their subsequent uses in accordance with this Agreement.
#
# **4.3. Derivatives.** By entering into this Agreement, You accept that any Derivatives that You may create or that may be created for You shall be subject to the restrictions set out in Section 3 of this Agreement.
#
# # 5. Liability
# **5.1. Limitation of liability.** In no event, unless required by applicable law (such as deliberate and grossly negligent acts) or agreed to in writing, shall Perceptron, Inc. be liable to You for damages, including any direct, indirect, special, incidental, or consequential damages of any character arising as a result of this Agreement or out of the use or inability to use the Perceptron Models and Derivatives (including but not limited to damages for loss of data, loss of goodwill, loss of expected profit or savings, work stoppage, computer failure or malfunction, or any damage caused by malware or security breaches), even if  Perceptron, Inc. has been advised of the possibility of such damages.
#
# **5.2. Indemnification.** You agree to indemnify and hold harmless Perceptron, Inc. from and against any claims, damages, or losses arising out of or related to Your use or Distribution of the Perceptron Models and Derivatives.
#
# ## 6. Warranty
# **6.1. Disclaimer.** Unless required by applicable law or agreed to in writing, Perceptron, Inc. provides the Perceptron Models and Derivatives on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, any warranties or conditions of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE. Perceptron, Inc. does not represent nor warrant that the Perceptron Models and Derivatives will be error-free, meet Your or any third party’s requirements, be secure or will allow You or any third party to achieve any kind of result or generate any kind of content. You are solely responsible for determining the appropriateness of using or Distributing the Perceptron Models and Derivatives and assume any risks associated with Your exercise of rights under this Agreement.
#
# # 7. Termination
# **7.1. Term.** This Agreement is effective as of the date of your acceptance of this Agreement or access to the concerned Perceptron Models or Derivatives and will continue until terminated in accordance with the following terms.
#
# **7.2. Termination.** Perceptron, Inc. may terminate this Agreement at any time if You are in breach of this Agreement. Upon termination of this Agreement, You must cease to use all Perceptron Models and Derivatives and shall permanently delete any copy thereof. Sections 5, 6, 7 and 8 shall survive the termination of this Agreement.
#
# **7.3. Litigation.** If You initiate any legal action or proceedings against Us or any other entity (including a cross-claim or counterclaim in a lawsuit), alleging that the Model or a Derivative, or any part thereof, infringe upon intellectual property or other rights owned or licensable by You, then any licenses granted to You under this Agreement will immediately terminate as of the date such legal action or claim is filed or initiated.
#
# # 8. General provisions
# 8.1. Governing Law. This Agreement will be governed by and construed in accordance with the laws of the State of Washington, without regard to its conflict of law principles.
#
# 8.2. Jurisdiction. The state and federal courts located in King County, Washington shall have exclusive jurisdiction over any dispute arising out of or relating to this Agreement, and You and We consent to personal jurisdiction and venue in such courts.
#
# **8.3. Severability.** If any provision of this Agreement is held to be invalid, illegal or unenforceable, the remaining provisions shall be unaffected thereby and remain valid as if such provision had not been set forth herein.
#
# # 9. Definitions
# **“Agreement”**: means this Perceptron, Inc. Non-Production License agreement governing the access, use, and Distribution of the Perceptron Models and Derivatives.
#
# **“Derivative”**: means any (i) modified version of the Perceptron Model (including but not limited to any customized or fine-tuned version thereof), (ii) work based on the Perceptron Model, or (iii) any other derivative work thereof. For the avoidance of doubt, Outputs are not considered as Derivatives under this Agreement.
#
# **“Distribution”**, **“Distributing”**, **“Distribute”** or **“Distributed”**: means providing or making available, by any means, a copy of the Perceptron Models and/or the Derivatives as the case may be, subject to Section 3 of this Agreement.
#
# **“Perceptron, Inc.”**, **“We”** or **“Us”**: means Perceptron, Inc., a Delaware corporation with its principal place of business at 10900 NE 8th St Suite 613, Bellevue, WA 98004.
#
# **“Perceptron Model”**: means the foundational large language model(s), and its elements which include algorithms, software, instructed checkpoints, parameters, source code (inference code, evaluation code and, if applicable, fine-tuning code) and any other elements associated thereto made available by Perceptron, Inc. under this Agreement, including, if any, the technical documentation, manuals and instructions for the use and operation thereof.
#
# **“Non-Production Environment”**: means any setting, use case, or application of the Perceptron Models or Derivatives that expressly excludes live, real-world conditions, commercial operations, revenue-generating activities, or direct interactions with or impacts on end users (such as, for instance, Your employees or customers). Non-Production Environment may include, but is not limited to, any setting, use case, or application for research, development, testing, quality assurance, training, internal evaluation (other than any internal usage by employees in the context of the company’s business activities), and demonstration purposes.
#
# **“Outputs”**: means any content generated by the operation of the Perceptron Models or the Derivatives from a prompt (i.e., text instructions) provided by users. For the avoidance of doubt, Outputs do not include any components of a Perceptron Models, such as any fine-tuned versions of the Perceptron Models, the weights, or parameters.
#
# **“Personal”**: means any use of a Perceptron Model or a Derivative that is (i) solely for personal, non-profit and non-commercial purposes and (ii) not directly or indirectly connected to any commercial activities, business operations, or employment responsibilities. For illustration purposes, Personal use of a Model or a Derivative does not include any usage by individuals employed in companies in the context of their daily tasks, any activity that is intended to generate revenue, or that is performed on behalf of a commercial entity.
#
# **“You”**: means the individual or entity entering into this Agreement with Perceptron, Inc..


import copy
from typing import Any, Optional, Union

from ...configuration_utils import PreTrainedConfig, PretrainedConfig, layer_type_validation
from ...modeling_rope_utils import rope_config_validation
from ...models.qwen3.configuration_qwen3 import Qwen3Config


class IsaacVisionConfig(PreTrainedConfig):
    """Vision configuration for Isaac with Pixel Shuffle support.

    Extends Siglip2VisionConfig with additional fields for pixel shuffle.

    Args:
        pixel_shuffle_scale_factor (`int`, *optional*, defaults to 1):
            Spatial factor applied before pixel shuffle reduces the resolution.
        num_patches (`int`, *optional*, defaults to 256):
            Maximum number of learnable positional embeddings to initialize.
    """

    model_type = "isaac_vision"
    base_config_key = "vision_config"
    _attn_implementation: Optional[str] = None

    def __init__(
        self,
        hidden_size=768,
        intermediate_size=3072,
        num_hidden_layers=12,
        num_attention_heads=12,
        num_channels=3,
        num_patches=256,
        patch_size=16,
        hidden_act="gelu_pytorch_tanh",
        layer_norm_eps=1e-6,
        attention_dropout=0.0,
        pixel_shuffle_scale_factor=1,
        **kwargs,
    ):
        super().__init__(**kwargs)

        self.hidden_size = hidden_size
        self.intermediate_size = intermediate_size
        self.num_hidden_layers = num_hidden_layers
        self.num_attention_heads = num_attention_heads
        self.num_channels = num_channels
        self.patch_size = patch_size
        self.attention_dropout = attention_dropout
        self.layer_norm_eps = layer_norm_eps
        self.hidden_act = hidden_act
        self.num_patches = num_patches

        # Add our custom fields
        self.pixel_shuffle_scale_factor = pixel_shuffle_scale_factor

        if self._attn_implementation is None:
            self._attn_implementation = "flash_attention_2"


class IsaacConfig(PretrainedConfig):
    """Configuration class for Isaac multimodal model.

    This configuration corresponds to checkpoints such as
    [Perceptron/isaac-base](https://huggingface.co/Perceptron/isaac-base).
    """

    model_type = "isaac"
    sub_configs = {"vision_config": IsaacVisionConfig, "text_config": Qwen3Config}
    image_processor_type = "IsaacImageProcessor"
    _TEXT_CONFIG_FIELDS = {
        "attention_bias",
        "attention_dropout",
        "head_dim",
        "hidden_act",
        "hidden_size",
        "initializer_range",
        "intermediate_size",
        "layer_types",
        "max_position_embeddings",
        "max_window_layers",
        "num_attention_heads",
        "num_hidden_layers",
        "num_key_value_heads",
        "rope_parameters",
        "rope_theta",
        "rms_norm_eps",
        "sliding_window",
        "tie_word_embeddings",
        "use_cache",
        "use_sliding_window",
        "vocab_size",
    }

    def __init__(
        self,
        vision_config: Optional[IsaacVisionConfig] = None,
        text_config: Optional[Union[Qwen3Config, dict]] = None,
        vision_rescale_factor: float = 1 / 255,
        max_sequence_length: int = 16384,
        vision_token: str = "<image>",
        **kwargs,
    ):
        resolved_text_config = kwargs.pop("text_config", text_config)
        if isinstance(resolved_text_config, Qwen3Config):
            text_config_kwargs = copy.deepcopy(resolved_text_config.to_dict())
        elif isinstance(resolved_text_config, dict):
            text_config_kwargs = copy.deepcopy(resolved_text_config)
        elif resolved_text_config is None:
            text_config_kwargs = {}
        else:
            raise TypeError("`text_config` must be a mapping or `Qwen3Config` instance when provided.")

        forwarded_text_keys = {key: kwargs.pop(key) for key in list(kwargs.keys()) if key in self._TEXT_CONFIG_FIELDS}
        text_config_kwargs.update(forwarded_text_keys)

        self._text_config_user_dict = copy.deepcopy(text_config_kwargs) if text_config_kwargs else {}

        self.text_config = self.sub_configs["text_config"](**text_config_kwargs)

        super().__init__(**kwargs)

        text_config = self.text_config
        self.layer_types = getattr(text_config, "layer_types", None)
        if self.layer_types is None:
            self.layer_types = [
                "sliding_attention"
                if getattr(text_config, "use_sliding_window", False)
                and getattr(text_config, "sliding_window", None) is not None
                and getattr(text_config, "max_window_layers", None) is not None
                and i >= text_config.max_window_layers
                else "full_attention"
                for i in range(text_config.num_hidden_layers)
            ]
        layer_type_validation(self.layer_types, text_config.num_hidden_layers)

        use_sliding_window = getattr(text_config, "use_sliding_window", False)
        sliding_window = getattr(text_config, "sliding_window", None)
        self.sliding_window = sliding_window if use_sliding_window else None
        self.max_window_layers = getattr(text_config, "max_window_layers", None)

        rope_params = copy.deepcopy(getattr(text_config, "rope_parameters", None))
        self.rope_parameters = rope_params
        if rope_params is not None:
            text_config.rope_parameters = copy.deepcopy(rope_params)

        rope_config_validation(self)

        # Handle vision config - either dict or IsaacVisionConfig instance
        if isinstance(vision_config, dict):
            self._vision_config_user_dict = copy.deepcopy(vision_config)
            self.vision_config = self.sub_configs["vision_config"](**vision_config)
        elif isinstance(vision_config, IsaacVisionConfig):
            self._vision_config_user_dict = vision_config.to_dict()
            self.vision_config = vision_config
        elif vision_config is None:
            self._vision_config_user_dict = {}
            self.vision_config = self.sub_configs["vision_config"]()

        # Vision normalization parameters
        self.vision_rescale_factor = float(vision_rescale_factor)

        # Processing parameters
        self.max_sequence_length = max_sequence_length
        self.vision_token = vision_token

    def get_text_config(self, *_, **kwargs) -> Qwen3Config:
        # Accept optional decoder/encoder flags to align with HF composite configs
        kwargs.pop("decoder", None)
        kwargs.pop("encoder", None)
        return self.text_config

    def _get_text_attr(self, name: str, default: Any = None):
        return getattr(self.text_config, name, default)

    def _set_text_attr(self, name: str, value: Any):
        setattr(self.text_config, name, value)
        if name in {"rope_parameters", "rope_theta"}:
            rope_params = copy.deepcopy(getattr(self.text_config, "rope_parameters", None))
            self.rope_parameters = rope_params
        if hasattr(self, "_text_config_user_dict"):
            if isinstance(value, dict):
                self._text_config_user_dict[name] = copy.deepcopy(value)
            else:
                self._text_config_user_dict[name] = value

    def to_diff_dict(self) -> dict[str, Any]:
        diff = super().to_diff_dict()
        if getattr(self, "_text_config_user_dict", None):
            diff["text_config"] = copy.deepcopy(self._text_config_user_dict)
        if getattr(self, "_vision_config_user_dict", None):
            diff["vision_config"] = copy.deepcopy(self._vision_config_user_dict)
        return diff

    @property
    def hidden_size(self) -> int:
        return int(self._get_text_attr("hidden_size"))

    @hidden_size.setter
    def hidden_size(self, value: int) -> None:
        self._set_text_attr("hidden_size", value)

    @property
    def vocab_size(self) -> int:
        return int(self._get_text_attr("vocab_size"))

    @vocab_size.setter
    def vocab_size(self, value: int) -> None:
        self._set_text_attr("vocab_size", value)

    @property
    def max_position_embeddings(self) -> int:
        return int(self._get_text_attr("max_position_embeddings"))

    @max_position_embeddings.setter
    def max_position_embeddings(self, value: int) -> None:
        self._set_text_attr("max_position_embeddings", value)

    @property
    def tie_word_embeddings(self) -> bool:
        return bool(self._get_text_attr("tie_word_embeddings", False))

    @tie_word_embeddings.setter
    def tie_word_embeddings(self, value: bool) -> None:
        self._set_text_attr("tie_word_embeddings", value)

    @property
    def num_hidden_layers(self) -> int:
        return int(self._get_text_attr("num_hidden_layers"))

    @num_hidden_layers.setter
    def num_hidden_layers(self, value: int) -> None:
        self._set_text_attr("num_hidden_layers", value)

    @property
    def num_attention_heads(self) -> int:
        return int(self._get_text_attr("num_attention_heads"))

    @num_attention_heads.setter
    def num_attention_heads(self, value: int) -> None:
        self._set_text_attr("num_attention_heads", value)

    @property
    def num_key_value_heads(self) -> int:
        return int(self._get_text_attr("num_key_value_heads", self.num_attention_heads))

    @num_key_value_heads.setter
    def num_key_value_heads(self, value: int) -> None:
        self._set_text_attr("num_key_value_heads", value)

    @property
    def head_dim(self) -> int:
        return int(self._get_text_attr("head_dim"))

    @head_dim.setter
    def head_dim(self, value: int) -> None:
        self._set_text_attr("head_dim", value)

    @property
    def intermediate_size(self) -> int:
        return int(self._get_text_attr("intermediate_size"))

    @intermediate_size.setter
    def intermediate_size(self, value: int) -> None:
        self._set_text_attr("intermediate_size", value)

    @property
    def hidden_act(self) -> str:
        return self._get_text_attr("hidden_act")

    @hidden_act.setter
    def hidden_act(self, value: str) -> None:
        self._set_text_attr("hidden_act", value)

    @property
    def initializer_range(self) -> float:
        return float(self._get_text_attr("initializer_range"))

    @initializer_range.setter
    def initializer_range(self, value: float) -> None:
        self._set_text_attr("initializer_range", value)

    @property
    def rms_norm_eps(self) -> float:
        return float(self._get_text_attr("rms_norm_eps"))

    @rms_norm_eps.setter
    def rms_norm_eps(self, value: float) -> None:
        self._set_text_attr("rms_norm_eps", value)

    @property
    def use_cache(self) -> bool:
        return bool(self._get_text_attr("use_cache", True))

    @use_cache.setter
    def use_cache(self, value: bool) -> None:
        self._set_text_attr("use_cache", value)

    @property
    def attention_bias(self) -> bool:
        return bool(self._get_text_attr("attention_bias", False))

    @attention_bias.setter
    def attention_bias(self, value: bool) -> None:
        self._set_text_attr("attention_bias", value)

    @property
    def attention_dropout(self) -> float:
        return float(self._get_text_attr("attention_dropout", 0.0))

    @attention_dropout.setter
    def attention_dropout(self, value: float) -> None:
        self._set_text_attr("attention_dropout", value)

    @property
    def rope_theta(self) -> float:
        rope_params = self.rope_parameters or {}
        if isinstance(rope_params, dict) and "rope_theta" in rope_params:
            return rope_params["rope_theta"]
        return getattr(self.text_config, "rope_theta", 10000.0)

    @rope_theta.setter
    def rope_theta(self, value: float) -> None:
        self._set_text_attr("rope_theta", value)

    @property
    def rope_scaling(self):
        return self.rope_parameters

    @rope_scaling.setter
    def rope_scaling(self, value):
        self.rope_parameters = value
        if hasattr(self, "text_config") and self.text_config is not None:
            self.text_config.rope_parameters = copy.deepcopy(value)

    @property
    def vision_attn_implementation(self) -> Optional[str]:
        value = getattr(self.vision_config, "_attn_implementation", None)
        if value is None:
            value = getattr(self.vision_config, "attn_implementation", None)
        return value

    @vision_attn_implementation.setter
    def vision_attn_implementation(self, value: Optional[str]) -> None:
        self.vision_config._attn_implementation = value
        if value is not None:
            self.vision_config.attn_implementation = value
        elif hasattr(self.vision_config, "attn_implementation"):
            delattr(self.vision_config, "attn_implementation")


__all__ = ["IsaacConfig"]
